# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 00:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField(default=18)),
                ('camera_type', models.CharField(default='Kodak', max_length=255)),
                ('job', models.CharField(default='', max_length=255)),
                ('url', models.URLField(default='')),
                ('photography_style', models.CharField(choices=[('MONO', 'Monochrome'), ('MACRO', 'Macro'), ('MICRO', 'Micro'), ('PORTRAIT', 'Portrait'), ('LANDSCAPE', 'Landscape')], default='PORTRAIT', max_length=255)),
                ('social_status', models.CharField(choices=[('PEASANT', 'Peasant'), ('BANDIT', 'Bandit'), ('YEOMAN', 'Yeoman'), ('MANATARMS', 'Man-at-arms'), ('KNIGHT', 'Knight'), ('ROYALTY', 'Royalty'), ('WIZARD', 'Wizard')], default='PEASANT', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
